name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:
    create:
        tags:
            - '*'
jobs:
    testsuite:
        name: Unittests
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.3', '8.4']

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: json, pdo
                  tools: pecl

            - name: Validate composer.json
              run: composer validate

            - name: Composer install
              run: composer install --prefer-dist --no-progress

            - name: Run PHPUnit
              run: vendor/bin/phpunit --exclude-group=amqp
